### ISSUE TITLE
LINKING ISSUE - jasmine-jQuery

### ISSUE THREAD

**Issue by SavageWilliam** [SavageWilliam/stopwatch#10]
We need to find a way to test our stopwatch.js files functions which access the DOM... How?

**Comment by SavageWilliam** [comment]
Resource: https://testdrivenwebsites.com/2010/07/29/html-fixtures-in-jasmine-using-jasmine-jquery/

**Comment by limeyb7** [comment]
Resolved by moving our HTML to spec runner file + switching to QUnit
